# Generated by Django 5.2.8 on 2025-11-30 18:58

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peer_id", models.CharField(max_length=200, unique=True)),
                ("host", models.CharField(max_length=200)),
                ("port", models.IntegerField()),
                ("last_seen", models.FloatField(default=time.time)),
            ],
        ),
    ]
