# Generated by Django 5.2.8 on 2025-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("certificate_pem", models.TextField()),
                ("issuer", models.CharField(max_length=500, null=True)),
                ("serial_number", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
